version: "3.8"
networks:
  caddy:
services:
  caddy:
    image: ${STUDIO_FRONTEND_IMAGE}
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
    ports:
      - "80:80"
      - "443:443"
    networks:
      - caddy
