version: "3.8"

services:
  caddy:
    build:
      context: ./frontend
      dockerfile: ./Dockerfile
    image: ${STUDIO_FRONTEND_IMAGE}
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./frontend/Caddyfile.dev:/etc/caddy/Caddyfile
      - caddy_data:/root/.local/share/caddy
      - caddy_config:/root/.config/caddy
    restart: unless-stopped

  backend:
    build:
      context: ./backend
      dockerfile: ./Dockerfile
    image: backend
    ports:
      - "60:60"
    volumes:
      - ./backend:/app

volumes:
  caddy_data:
  caddy_config:
