export const paintings = [
  {
    id: 1,
    title: "The Starry Night",
    artist: "Vincent van Gogh",
    desc: "This painting was created by Vincent van Gogh in 1889.",
    year: 1889,
    image: "001.JPG",
  },
  {
    id: 2,
    title: "The Starry Night",
    artist: "Vincent van Gogh",
    desc: "This painting was created by Vincent van Gogh in 1889.",
    year: 1889,
    image: "002.JPG",
  },
  {
    id: 3,
    title: "The Starry Night",
    artist: "Vincent van Gogh",
    desc: "This painting was created by Vincent van Gogh in 1889.",
    year: 1889,
    image: "003.JPG",
  },
  {
    id: 3,
    title: "The Starry Night",
    artist: "Vincent van Gogh",
    desc: "This painting was created by Vincent van Gogh in 1889.",
    year: 1889,
    image: "004.JPG",
  },
  {
    id: 3,
    title: "The Starry Night",
    artist: "Vincent van Gogh",
    desc: "This painting was created by Vincent van Gogh in 1889.",
    year: 1889,
    image: "003.JPG",
  },
  {
    id: 3,
    title: "The Starry Night",
    artist: "Vincent van Gogh",
    desc: "This painting was created by Vincent van Gogh in 1889.",
    year: 1889,
    image: "004.JPG",
  },
  {
    id: 3,
    title: "The Starry Night",
    artist: "Vincent van Gogh",
    desc: "This painting was created by Vincent van Gogh in 1889.",
    year: 1889,
    image: "005.JPG",
  },
  {
    id: 3,
    title: "The Starry Night",
    artist: "Vincent van Gogh",
    desc: "This painting was created by Vincent van Gogh in 1889.",
    year: 1889,
    image: "006.JPG",
  },
  {
    id: 3,
    title: "The Starry Night",
    artist: "Vincent van Gogh",
    desc: "This painting was created by Vincent van Gogh in 1889.",
    year: 1889,
    image: "007.JPG",
  },
  {
    id: 3,
    title: "The Starry Night",
    artist: "Vincent van Gogh",
    desc: "This painting was created by Vincent van Gogh in 1889.",
    year: 1889,
    image: "008.JPG",
  },
];
