export const paintings = [
  {
    id: 1,
    title: "The Starry Night",
    artist: "Vincent van Gogh",
    year: 1889,
    image: "001.JPG",
  },
  {
    id: 2,
    title: "The Starry Night",
    artist: "Vincent van Gogh",
    year: 1889,
    image: "002.JPG",
  },
  {
    id: 3,
    title: "The Starry Night",
    artist: "Vincent van Gogh",
    year: 1889,
    image: "003.JPG",
  },
  {
    id: 4,
    title: "The Starry Night",
    artist: "Vincent van Gogh",
    year: 1889,
    image: "003.JPG",
  },
  {
    id: 5,
    title: "The Starry Night",
    artist: "Vincent van Gogh",
    year: 1889,
    image: "003.JPG",
  },
  {
    id: 6,
    title: "The Starry Night",
    artist: "Vincent van Gogh",
    year: 1889,
    image: "003.JPG",
  },
  {
    id: 1,
    title: "The Starry Night",
    artist: "Vincent van Gogh",
    year: 1889,
    image: "003.JPG",
  },
  {
    id: 2,
    title: "The Starry Night",
    artist: "Vincent van Gogh",
    year: 1889,
    image: "003.JPG",
  },
  {
    id: 3,
    title: "The Starry Night",
    artist: "Vincent van Gogh",
    year: 1889,
    image: "003.JPG",
  },
  {
    id: 4,
    title: "The Starry Night",
    artist: "Vincent van Gogh",
    year: 1889,
    image: "003.JPG",
  },
  {
    id: 5,
    title: "The Starry Night",
    artist: "Vincent van Gogh",
    year: 1889,
    image: "003.JPG",
  },
  {
    id: 6,
    title: "The Starry Night",
    artist: "Vincent van Gogh",
    year: 1889,
    image: "003.JPG",
  },
];
