import { useEffect } from "react";

export const paintings = [
  {
    id: 1,
    title: "WATER",
    artist: "Amanda",
    tech: ["Spray paint", "Acrylic", "Gold paste"],
    height: 60,
    width: 50,
    year: 2024,
    image: "001.JPG",
  },
  {
    id: 2,
    title: "LIQUID FIRE",
    artist: "Amanda",
    tech: ["Spray paint", "Acrylic", "Gold paste"],
    desc: "Movement, layers, depth & light.",
    height: 65,
    width: 54,
    year: 2024,
    image: "002.JPG",
  },
  {
    id: 3,
    title: "INNER WORLD",
    artist: "Amanda",
    tech: ["Spray paint", "Acrylic", "Gold paste"],
    desc: "Still & calm portrait, while colorful and electric. ",
    height: 80,
    width: 60,
    year: 2024,
    image: "003.JPG",
  },
  {
    id: 4,
    title: "BLUE EASTER ISLAND",
    artist: "Amanda",
    tech: ["Spray paint", "Acrylic", "Gold paste"],
    desc: "Inspired by the easter islands in Chile.",
    height: 100,
    width: 80,
    year: 2024,
    image: "004.JPG",
  },
  {
    id: 5,
    title: "LANZAROTE",
    artist: "Amanda",
    tech: ["Spray paint", "Acrylic", "Gold paste"],
    desc: "Inspired by the canary island Lanzarote.Volcanoes, the ocean and the black sand.",
    height: 80,
    width: 100,
    year: 2024,
    image: "005.JPG",
  },
  {
    id: 6,
    title: "ICE DIVA",
    artist: "Amanda",
    tech: ["Spray paint", "Acrylic", "Gold paste"],
    height: 100,
    width: 100,
    year: 2024,
    image: "006.JPG",
  },

  {
    id: 7,
    title: "ARBORIGINAL",
    artist: "Amanda",
    tech: ["Spray paint", "Acrylic", "Gold paste"],
    desc: "Spray paint, acrylic and golden paste.",
    height: 100,
    width: 80,
    year: 2024,
    image: "007.JPG",
  },
  {
    id: 8,
    title: "MEMORIES OF LANDSCAPE",
    artist: "Amanda",
    tech: ["Spray paint", "Acrylic", "Gold paste"],
    height: 100,
    width: 100,
    year: 2024,
    image: "008.JPG",
  },
  {
    id: 9,
    title: "COW BOY",
    artist: "Amanda",
    tech: ["Spray paint", "Acrylic", "Gold paste"],
    desc: "Spray paint, acrylic and golden paste.",
    height: 80,
    width: 80,
    year: 2024,
    image: "009.JPG",
  },
  {
    id: 10,
    title: "BOXER",
    artist: "Amanda",
    tech: ["Spray paint", "Acrylic"],
    height: 100,
    width: 80,
    year: 2024,
    image: "010.JPG",
  },

  {
    id: 11,
    title: "REFLECTIONS",
    artist: "Amanda",
    tech: ["Spray paint", "Acrylic", "Golden paste", "Oil sticks"],
    height: 100,
    width: 80,
    year: 2024,
    image: "011.JPG",
  },
  {
    id: 12,
    title: "SHADES OF LIFE",
    artist: "Amanda",
    tech: ["Spray paint", "Acrylic", "Golden paste", "Oil sticks"],
    height: 100,
    width: 80,
    year: 2024,
    image: "012.JPG",
  },
  {
    id: 13,
    title: "FEMININE",
    artist: "Amanda",
    tech: ["Spray paint", "Acrylic", "Golden paste", "Oil sticks"],
    desc: "Spray paint, acrylic and golden paste.",
    height: 100,
    width: 80,
    year: 2024,
    image: "013.JPG",
  },
];

// Custom hooks
export const useScrollToTop = () => {
  useEffect(() => {
    window.scrollTo(0, 0);
  }, []);
};
